Implement a new feature that allows extending a running maintenance
kytos-ng/maintenance pull request #11
Opened 2021-06-08 19:48 UTC by ajoaoff

This PR fixes #8.

Description of the change
-----------------------------
A new endpoint was created to extend a running maintenance. The API documentation and the tests were also updated.

Release notes
---------------
- New REST API endpoint to extend a running maintenance.

2021-06-10 13:41 UTC, ArturoQuintana requested changes
Keep a coherent relationship between the response status code.

2021-06-10 13:41 UTC, ArturoQuintana commented on openapi.yml
> +        '201':
'200':

2021-06-10 18:17 UTC, ajoaoff commented on openapi.yml
> +        '201':
Solved in the new commit

2021-06-14 13:59 UTC, italovalcy reviewed
Hi @ajoaoff I don't know if I missed something, but this PR is just for the documentation, right? From the description, I was expecting to have the actual code that implements the new feature of extending the running MW

2021-06-14 15:45 UTC, ajoaoff commented
> Hi @ajoaoff I don't know if I missed something, but this PR is just for the documentation, right? From the description, I was expecting to have the actual code that implements the new feature of extending the running MW

I made some mistake when I last updated the `openapi.yml` file and the changes in `main.py` just vanished.

2021-06-14 15:49 UTC, ArturoQuintana commented
Hi @ajoaoff, that's maybe the reason the test is not working properly.

2021-06-14 16:18 UTC, ArturoQuintana approved these changes

2021-06-22 18:52 UTC, ArturoQuintana approved these changes

2021-06-22 19:01 UTC, ArturoQuintana approved these changes

2021-07-14 12:18 UTC, merged